spring:
  application:
    name: entire-photo-backend-main
  datasource:
    url: jdbc:postgresql://localhost:5432/entire_photos
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 35MB
      max-request-size: 35MB
      file-size-threshold: -1
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    username: admin
    password: secret
    template:
      default-receive-queue: user-registration-queue
      exchange: user-registration-exchange
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health

server:
  error:
    include-exception: true #include-message: always
    include-message: always
    include-binding-errors: always
  port: 1001

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
